### ISSUE TITLE
Undefined _handleAct call in "Player" component.

### ISSUE THREAD

**Issue by anjackthemage** [SlushFilter/TheOtherThing#7]
I threw in some console log commands to see what state the _handleAct method was receiving from the "Act" event:

"_handleAct : function(data) {
        console.log(`Player actioning 1: ${data.state}`);
        if(data.state === false) { return; }
        console.log(`Player actioning 2: ${data.state}`);
        "

This is the output when I hit "enter" while facing an NPC:

"Player actioning 1: true
tot.player.js:19 Player actioning 2: true
tot.player.js:42 Probe @ X:398 Y:375
tot.menu.js:198 Creating menu.
tot.player.js:17 Player actioning 1: undefined
tot.player.js:19 Player actioning 2: undefined
tot.player.js:42 Probe @ X:398 Y:375
tot.menu.js:198 Creating menu.
tot.menu.js:293 Setting attributes.
tot.menu.js:293 Setting attributes.
tot.player.js:17 Player actioning 1: false"

So it appears that the "_handleAct" method is being called a second time. I confirmed that the "Act" even only gets sent once, so perhaps there is something else calling "_handleAct".

**Comment by anjackthemage** [comment]
Recommend replacing "if(data.state === false)" with "if(!data.state)". This will check for Boolean values instead of doing an object comparison.

Alternatively you could use "if(data.state === true)" and encapsulate the rest of the method in {}.

**Comment by SlushFilter** [comment]
Unable to recreate. ( possibly fixed during refactoring? )
Closing ticket.
